-- Nico Fit V2 - sync hardening (non-destructive and idempotent)
-- Run before deploying the matching frontend.

create table if not exists public.sync_tombstones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entity text not null,
  record_key text not null,
  deleted_at timestamptz not null default now(),
  unique (user_id, entity, record_key)
);

alter table public.sync_tombstones enable row level security;

drop policy if exists "sync_tombstones_select_own" on public.sync_tombstones;
create policy "sync_tombstones_select_own" on public.sync_tombstones for select using (auth.uid() = user_id);
drop policy if exists "sync_tombstones_insert_own" on public.sync_tombstones;
create policy "sync_tombstones_insert_own" on public.sync_tombstones for insert with check (auth.uid() = user_id);
drop policy if exists "sync_tombstones_update_own" on public.sync_tombstones;
create policy "sync_tombstones_update_own" on public.sync_tombstones for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "sync_tombstones_delete_own" on public.sync_tombstones;
create policy "sync_tombstones_delete_own" on public.sync_tombstones for delete using (auth.uid() = user_id);

create index if not exists sync_tombstones_user_deleted_idx on public.sync_tombstones (user_id, deleted_at desc);
