-- Nico Fit V2 - migración no destructiva
-- Ejecutar una vez en Supabase > SQL Editor.

alter table public.readiness add column if not exists pain_area text not null default '';

create table if not exists public.football_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  session_type text not null,
  duration_minutes smallint not null check (duration_minutes >= 0),
  rpe smallint not null check (rpe between 1 and 10),
  minutes_played smallint not null default 0 check (minutes_played >= 0),
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, date, session_type)
);

create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  day text not null,
  label text not null,
  started_at timestamptz,
  ended_at timestamptz,
  duration_minutes smallint not null default 0 check (duration_minutes >= 0),
  rpe smallint not null default 0 check (rpe between 0 and 10),
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, date, label)
);

alter table public.football_sessions enable row level security;
alter table public.workout_sessions enable row level security;

drop policy if exists "football_select_own" on public.football_sessions;
create policy "football_select_own" on public.football_sessions for select using (auth.uid() = user_id);
drop policy if exists "football_insert_own" on public.football_sessions;
create policy "football_insert_own" on public.football_sessions for insert with check (auth.uid() = user_id);
drop policy if exists "football_update_own" on public.football_sessions;
create policy "football_update_own" on public.football_sessions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "football_delete_own" on public.football_sessions;
create policy "football_delete_own" on public.football_sessions for delete using (auth.uid() = user_id);

drop policy if exists "workout_sessions_select_own" on public.workout_sessions;
create policy "workout_sessions_select_own" on public.workout_sessions for select using (auth.uid() = user_id);
drop policy if exists "workout_sessions_insert_own" on public.workout_sessions;
create policy "workout_sessions_insert_own" on public.workout_sessions for insert with check (auth.uid() = user_id);
drop policy if exists "workout_sessions_update_own" on public.workout_sessions;
create policy "workout_sessions_update_own" on public.workout_sessions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "workout_sessions_delete_own" on public.workout_sessions;
create policy "workout_sessions_delete_own" on public.workout_sessions for delete using (auth.uid() = user_id);

create index if not exists football_sessions_user_date_idx on public.football_sessions (user_id, date desc);
create index if not exists workout_sessions_user_date_idx on public.workout_sessions (user_id, date desc);
