-- Gym + Fútbol - esquema inicial para Supabase
-- Ejecutar una sola vez desde Supabase > SQL Editor > New query.

create table if not exists public.readiness (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  sleep smallint not null check (sleep between 1 and 5),
  energy smallint not null check (energy between 1 and 5),
  fatigue smallint not null check (fatigue between 1 and 5),
  pain smallint not null check (pain between 0 and 10),
  updated_at timestamptz not null default now(),
  unique (user_id, date)
);

create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  day text not null,
  exercise text not null,
  sets jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, date, exercise)
);

create table if not exists public.match_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  energy smallint not null check (energy between 1 and 5),
  legs smallint not null check (legs between 1 and 5),
  performance smallint not null check (performance between 1 and 5),
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, date)
);

alter table public.readiness enable row level security;
alter table public.workouts enable row level security;
alter table public.match_reviews enable row level security;

-- Policies: cada usuario solo puede operar sobre sus propias filas.
drop policy if exists "readiness_select_own" on public.readiness;
create policy "readiness_select_own" on public.readiness
for select using (auth.uid() = user_id);

drop policy if exists "readiness_insert_own" on public.readiness;
create policy "readiness_insert_own" on public.readiness
for insert with check (auth.uid() = user_id);

drop policy if exists "readiness_update_own" on public.readiness;
create policy "readiness_update_own" on public.readiness
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "readiness_delete_own" on public.readiness;
create policy "readiness_delete_own" on public.readiness
for delete using (auth.uid() = user_id);

drop policy if exists "workouts_select_own" on public.workouts;
create policy "workouts_select_own" on public.workouts
for select using (auth.uid() = user_id);

drop policy if exists "workouts_insert_own" on public.workouts;
create policy "workouts_insert_own" on public.workouts
for insert with check (auth.uid() = user_id);

drop policy if exists "workouts_update_own" on public.workouts;
create policy "workouts_update_own" on public.workouts
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "workouts_delete_own" on public.workouts;
create policy "workouts_delete_own" on public.workouts
for delete using (auth.uid() = user_id);

drop policy if exists "match_reviews_select_own" on public.match_reviews;
create policy "match_reviews_select_own" on public.match_reviews
for select using (auth.uid() = user_id);

drop policy if exists "match_reviews_insert_own" on public.match_reviews;
create policy "match_reviews_insert_own" on public.match_reviews
for insert with check (auth.uid() = user_id);

drop policy if exists "match_reviews_update_own" on public.match_reviews;
create policy "match_reviews_update_own" on public.match_reviews
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "match_reviews_delete_own" on public.match_reviews;
create policy "match_reviews_delete_own" on public.match_reviews
for delete using (auth.uid() = user_id);

create index if not exists readiness_user_date_idx on public.readiness (user_id, date desc);
create index if not exists workouts_user_date_idx on public.workouts (user_id, date desc);
create index if not exists match_reviews_user_date_idx on public.match_reviews (user_id, date desc);
