-- Supabase staging-only bootstrap. Never run against the production project.
-- Passwords are injected into session-local settings by the generated bundle.

create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  day text not null,
  label text not null,
  started_at timestamptz,
  ended_at timestamptz,
  duration_minutes smallint not null default 0,
  rpe smallint not null default 0,
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, date, label)
);

create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  day text not null,
  exercise text not null,
  sets jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, date, exercise)
);

create table if not exists public.sync_tombstones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entity text not null,
  record_key text not null,
  deleted_at timestamptz not null default now(),
  unique (user_id, entity, record_key)
);

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
)
values
  (
    '00000000-0000-0000-0000-000000000000',
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    'authenticated', 'authenticated', 'nico-fit-v3-a@example.invalid',
    extensions.crypt(current_setting('nico_fit.staging_password_a'), extensions.gen_salt('bf')),
    now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', ''
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    'authenticated', 'authenticated', 'nico-fit-v3-b@example.invalid',
    extensions.crypt(current_setting('nico_fit.staging_password_b'), extensions.gen_salt('bf')),
    now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', ''
  )
on conflict (id) do update
set encrypted_password = excluded.encrypted_password,
    email_confirmed_at = excluded.email_confirmed_at,
    updated_at = now();

insert into auth.identities (
  id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at
)
select
  gen_random_uuid(), u.email, u.id,
  jsonb_build_object('sub', u.id::text, 'email', u.email),
  'email', now(), now(), now()
from auth.users u
where u.id in (
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'
)
on conflict (provider_id, provider) do update
set identity_data = excluded.identity_data,
    updated_at = now();
