-- Minimal Supabase-compatible objects for the isolated PostgreSQL dry run.
-- This file is test-only and must never be used as a production migration.

create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;

create schema auth;
create table auth.users (
  id uuid primary key,
  email text unique
);

create or replace function auth.uid()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

grant usage on schema auth to anon, authenticated, service_role;
grant execute on function auth.uid() to anon, authenticated, service_role;

create table public.workout_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  day text not null,
  label text not null,
  started_at timestamptz,
  ended_at timestamptz,
  duration_minutes smallint not null default 0,
  rpe smallint not null default 0,
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, date, label)
);

create table public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  day text not null,
  exercise text not null,
  sets jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, date, exercise)
);

create table public.sync_tombstones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entity text not null,
  record_key text not null,
  deleted_at timestamptz not null default now(),
  unique (user_id, entity, record_key)
);
