import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', B='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const sql=name=>readFile(new URL(`../supabase/${name}`,import.meta.url),'utf8');
async function database(){const db=new PGlite();for(const name of ['test-v3-local-bootstrap.sql','migration-v3-schema.sql','migration-v3-observability.sql','migration-v3-audit-retention.sql','migration-v3-audit-retention.sql'])await db.exec(await sql(name));await db.exec(`insert into auth.users(id) values ('${A}'),('${B}');`);return db;}
async function add(db,{id,user=A,type='sync_failure',kind='transient'}){const isResolution=type==='conflict_resolution';const columns=isResolution?'event_id,user_id,event_type,entity,entity_id,strategy,occurred_at':'event_id,user_id,event_type,error_kind,occurred_at';const values=isResolution?`'${id}','${user}','conflict_resolution','football_sessions','11111111-1111-4111-8111-111111111111','defer',clock_timestamp()`:`'${id}','${user}','sync_failure','${kind}',clock_timestamp()`;await db.exec(`insert into nico_fit_v3.operational_audit(${columns}) values (${values});`);}
test('audit retention migration is idempotent, client delete is unavailable and admin routines are not callable by clients',async()=>{const db=await database();try{await add(db,{id:'00000000-0000-4000-8000-000000000001'});await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${A}',false);`);await assert.rejects(db.exec('delete from nico_fit_v3.operational_audit'),e=>e.code==='42501');await assert.rejects(db.exec('select * from nico_fit_v3.audit_retention_preview()'),e=>e.code==='42501');await assert.rejects(db.exec("select * from nico_fit_v3.purge_operational_audit('retention')"),e=>e.code==='42501');await db.exec('reset role');}finally{await db.close();}});
test('preview applies retention categories and explicit retention purge only removes eligible metadata',async()=>{const db=await database();try{await add(db,{id:'00000000-0000-4000-8000-000000000011',kind:'transient'});await add(db,{id:'00000000-0000-4000-8000-000000000012',kind:'auth'});await add(db,{id:'00000000-0000-4000-8000-000000000013',kind:'permanent'});await add(db,{id:'00000000-0000-4000-8000-000000000014',type:'conflict_resolution'});await db.exec("alter table nico_fit_v3.operational_audit disable trigger audit_append_only; update nico_fit_v3.operational_audit set received_at = case event_id when '00000000-0000-4000-8000-000000000011' then clock_timestamp() - interval '31 days' when '00000000-0000-4000-8000-000000000012' then clock_timestamp() - interval '91 days' else clock_timestamp() - interval '100 days' end; alter table nico_fit_v3.operational_audit enable trigger audit_append_only;");await db.exec('set role service_role');const preview=await db.query('select * from nico_fit_v3.audit_retention_preview()');const counts=Object.fromEntries(preview.rows.map(r=>[r.category,Number(r.eligible_count)]));assert.equal(counts['sync_failure:transient'],1);assert.equal(counts['sync_failure:auth'],1);assert.equal(counts['sync_failure:permanent'],0);assert.equal(counts.conflict_resolution,0);const purged=await db.query("select * from nico_fit_v3.purge_operational_audit('retention', null, false, clock_timestamp())");assert.deepEqual(Object.fromEntries(purged.rows.map(r=>[r.category,Number(r.purged_count)])),{'sync_failure:auth':1,'sync_failure:transient':1});await db.exec('reset role');assert.equal(Number((await db.query('select count(*)::int as count from nico_fit_v3.operational_audit')).rows[0].count),2);}finally{await db.close();}});
test('account deletion purge requires explicit confirmation and clears FK-restricted audit only for approved user',async()=>{const db=await database();try{await add(db,{id:'00000000-0000-4000-8000-000000000021',user:A,kind:'permanent'});await add(db,{id:'00000000-0000-4000-8000-000000000022',user:B,kind:'permanent'});await db.exec('set role service_role');await assert.rejects(db.exec(`select * from nico_fit_v3.purge_operational_audit('account_deletion','${A}',false)`),e=>e.code==='22023');const result=await db.query(`select * from nico_fit_v3.purge_operational_audit('account_deletion','${A}',true)`);assert.deepEqual(result.rows.map(r=>[r.category,Number(r.purged_count)]),[['sync_failure:permanent',1]]);await db.exec('reset role');await db.exec(`delete from auth.users where id='${A}';`);assert.equal(Number((await db.query(`select count(*)::int as count from nico_fit_v3.operational_audit where user_id='${B}'`)).rows[0].count),1);}finally{await db.close();}});
test('policy documentation prohibits secrets and automatic client purges',async()=>{const doc=await readFile(new URL('../docs/v3-audit-retention-policy.md',import.meta.url),'utf8');for(const text of ['No existe tarea programada','No usar `DELETE` normal','tokens','contraseñas','ON DELETE RESTRICT'])assert.ok(doc.includes(text));});

test('staging admin runner requires a private administrative connection and hard staging guards',async()=>{
  const runner=await readFile(new URL('../scripts/v3-audit-retention-staging-admin.mjs',import.meta.url),'utf8');
  assert.match(runner,/tmydirzzlmlmtjgwqcgh/);
  assert.match(runner,/xaklsoqyzwowtjwcpwmb/);
  assert.match(runner,/SUPABASE_STAGING_DATABASE_URL/);
  assert.match(runner,/SUPABASE_STAGING_POSTGRES_URL/);
  assert.match(runner,/service\[_-\]\?role/);
  assert.match(runner,/migrationAppliedTwice/);
});
