import test from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory} from 'fake-indexeddb';
import {V3LocalRepository} from '../js/v3/repository.js';
import {V3ConflictService} from '../js/v3/conflict-service.js';
import {isV3ConflictsEnabled} from '../js/v3/feature-flags.js';
import {V3SyncEngine} from '../js/v3/sync-engine.js';
import {remotePayloadForOperation} from '../js/v3/sync-protocol.js';
import {V3ConflictUI} from '../js/v3/conflict-ui.js';
import {INTERNAL_STORES,requestResult,transactionDone} from '../js/v3/indexed-db.js';
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',B='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
async function fixture(entity='football_sessions',extra={}){
  const db=new IDBFactory(),repository=await V3LocalRepository.open({indexedDB:db,userId:A,featureEnabled:true});
  if(entity==='session_exercises'||entity==='exercise_sets'){
    await repository.create('workout_sessions',{session_date:'2026-09-15'},{id:'parent-session'});
    await repository.create('session_exercises',{session_id:'parent-session',position:0,name_snapshot:'Squat'},{id:'parent-exercise'});
  }
  const payload={local_date:'2026-09-15',session_date:'2026-09-15',session_id:'parent-session',session_exercise_id:'parent-exercise',position:1,reps:8,rpe:7,...extra};
  const local=await repository.create(entity,payload);const remote={...local,user_id:A,version:3,rpe:8,...extra};delete remote.owner_id;
  await repository.recordConflict({entity,recordId:local.id,operationIds:(await repository.unresolvedOperations(entity,local.id)).map(row=>row.operation_id),reason:'remote_changed',localPayload:local,remotePayload:remote});
  const service=new V3ConflictService({repository,locks:null});return {db,repository,service,local,remote,view:(await service.list())[0]};
}
test('conflict read model exposes both sides, explanations and no implicit decision',async()=>{const f=await fixture();assert.equal(f.view.local.rpe,7);assert.equal(f.view.remote.rpe,8);assert.ok(f.view.explanation);assert.equal(await f.service.count(),1);assert.equal((await f.service.history()).length,0);f.repository.close();});
test('accept remote archives local operations and preserves auditable resolved conflict',async()=>{const f=await fixture();const audit=await f.service.resolve(f.view,'accept_remote');assert.equal(audit.owner_id,A);assert.equal(audit.entity,'football_sessions');assert.equal(audit.remote_version,3);assert.ok(audit.resolved_at);assert.equal((await f.repository.get('football_sessions',f.local.id)).rpe,8);assert.equal((await f.repository.listOperations())[0].status,'superseded');assert.equal((await f.service.list({status:'resolved'})).length,1);f.repository.close();});
test('keep local offline creates new versioned operation and waits for real acknowledgement',async()=>{const f=await fixture();const audit=await f.service.resolve(f.view,'keep_local');const op=(await f.repository.listOperations()).find(row=>row.operation_id===audit.operation_ids[0]);assert.equal(op.base_remote_version,3);assert.equal(op.status,'pending');assert.equal((await f.service.list())[0].status,'resolution_pending');await f.repository.acknowledgeOperations([op.operation_id],{remoteRecord:{...f.remote,rpe:7,version:4}});assert.equal((await f.service.list())[0].status,'resolved');assert.equal((await f.service.history())[0].confirmation,'server_confirmed');f.repository.close();});
test('remote tombstone cannot be revived and both is not offered',async()=>{const f=await fixture('football_sessions',{deleted_at:'2026-09-15T10:00:00Z'});assert.deepEqual(f.view.strategies,['defer','accept_remote']);await assert.rejects(f.service.resolve(f.view,'keep_local'));await f.service.resolve(f.view,'accept_remote');assert.ok((await f.repository.get('football_sessions',f.local.id)).deleted_at);f.repository.close();});
test('stale local revision rejects resolution atomically',async()=>{const f=await fixture();await f.repository.update('football_sessions',f.local.id,{rpe:6});await assert.rejects(f.service.resolve(f.view,'accept_remote'),/revision/i);assert.equal((await f.service.history()).length,0);f.repository.close();});
test('series never offer arbitrary duplication',async()=>{const f=await fixture('exercise_sets');assert.ok(!f.view.strategies.includes('keep_both'));await assert.rejects(f.service.resolve(f.view,'keep_both'));await f.service.resolve(f.view,'accept_remote');f.repository.close();});
test('session conflict resolves explicitly without offering incomplete subtree duplication',async()=>{const f=await fixture('workout_sessions');assert.ok(!f.view.strategies.includes('keep_both'));await f.service.resolve(f.view,'keep_local');assert.equal((await f.repository.get('workout_sessions',f.local.id)).sync_status,'pending');f.repository.close();});
test('both creates independent football occurrence and preserves original remote identity',async()=>{const f=await fixture();const decision=await f.service.resolve(f.view,'keep_both');assert.notEqual(decision.target_id,f.local.id);assert.equal((await f.repository.listRecords('football_sessions')).length,2);const op=(await f.repository.listOperations()).find(row=>row.operation_id===decision.operation_ids[0]);assert.equal(op.type,'insert');assert.equal(op.base_remote_version,null);await f.repository.acknowledgeOperations([op.operation_id],{remoteRecord:{...op.payload,user_id:A,version:1}});assert.equal((await f.service.list())[0].status,'resolved');f.repository.close();});
test('postpone keeps conflict open and records audit after reload',async()=>{const f=await fixture();await f.service.resolve(f.view,'defer',{note:'Revisar mañana'});f.repository.close();const repository=await V3LocalRepository.open({indexedDB:f.db,userId:A,featureEnabled:true}),service=new V3ConflictService({repository,locks:null});assert.equal(await service.count(),1);assert.equal((await service.history())[0].metadata.note,'Revisar mañana');repository.close();});
test('failed offline decision retries with same operation identity',async()=>{const f=await fixture();const audit=await f.service.resolve(f.view,'keep_local'),id=audit.operation_ids[0];await f.repository.setOperationStatus(id,'failed',{error:'offline'});await f.repository.retryOperation(id);assert.equal((await f.repository.listOperations()).find(row=>row.operation_id===id).status,'pending');assert.equal((await f.service.history()).length,1);f.repository.close();});
test('new server conflict reopens decision without losing previous audit',async()=>{const f=await fixture();const decision=await f.service.resolve(f.view,'keep_local');await f.repository.recordConflict({entity:'football_sessions',recordId:f.local.id,operationIds:decision.operation_ids,reason:'version_conflict',remotePayload:{...f.remote,version:5}});const view=(await f.service.list())[0];assert.equal(view.status,'open');assert.equal(view.decisions.length,1);await f.service.resolve(view,'keep_local');assert.equal((await f.service.history()).length,2);f.repository.close();});
test('cross-user conflict and decisions remain isolated',async()=>{const f=await fixture();await f.service.resolve(f.view,'defer');const other=await V3LocalRepository.open({indexedDB:f.db,userId:B,featureEnabled:true}),service=new V3ConflictService({repository:other,locks:null});assert.equal(await service.count(),0);assert.equal((await service.history()).length,0);await assert.rejects(service.resolve(f.view,'accept_remote'));other.close();f.repository.close();});
test('live lease prevents UI resolution and opening another repository from recovering in-flight work',async()=>{const f=await fixture();await f.repository.acquireLease(`nico-fit-v3-sync:${A}`,'worker');await assert.rejects(f.service.resolve(f.view,'keep_local'),/sincronización/);assert.equal((await f.service.history()).length,0);const [operation]=await f.repository.listOperations();await f.repository.setOperationStatus(operation.operation_id,'syncing');const second=await V3LocalRepository.open({indexedDB:f.db,userId:A,featureEnabled:true});assert.equal((await second.listOperations())[0].status,'syncing');second.close();f.repository.close();});
test('active session cannot be replaced under an editing user',async()=>{const f=await fixture('workout_sessions');await f.repository.commitLocalChanges([],{trainingState:{activeSessionId:f.local.id}});await assert.rejects(f.service.resolve(f.view,'accept_remote'),/active session/);assert.equal((await f.service.history()).length,0);f.repository.close();});
test('flag is opt-in and malformed values remain disabled',()=>{assert.equal(isV3ConflictsEnabled({getItem:()=>null}),false);assert.equal(isV3ConflictsEnabled({getItem:()=> 'true'}),true);});
test('resolved offline operation reaches server via existing sync engine',async()=>{
  const f=await fixture();await f.service.resolve(f.view,'keep_local');let server=f.remote,fail=true;
  const remote={authenticatedUserId:async()=>A,fetchChanges:async(entity,{cursor})=>entity==='football_sessions'&&!cursor?[server]:[],fetchById:async()=>server,mutate:async(operation,userId)=>{if(fail)throw new TypeError('offline');const payload=remotePayloadForOperation(operation,userId);assert.equal(payload.version,server.version+1);server={...server,...payload,updated_at:'2026-09-16T00:00:00Z'};return server;}};
  const engine=new V3SyncEngine({repository:f.repository,remote,featureEnabled:true,signalsSyncEnabled:true,locks:null});await engine.syncOnce();assert.equal((await f.service.list())[0].status,'resolution_pending');fail=false;
  const failed=(await f.repository.listOperations()).find(row=>row.status==='failed');assert.ok(failed);await f.repository.retryOperation(failed.operation_id);await engine.syncOnce();assert.equal(server.rpe,7);assert.equal((await f.service.list())[0].status,'resolved');assert.equal((await f.service.history())[0].confirmation,'server_confirmed');f.repository.close();
});
test('remote version changing after decision creates explicit conflict on next sync',async()=>{
  const f=await fixture();await f.service.resolve(f.view,'keep_local');const server={...f.remote,version:5,updated_at:'2026-09-16T00:00:00Z'};
  const remote={authenticatedUserId:async()=>A,fetchChanges:async(entity,{cursor})=>entity==='football_sessions'&&!cursor?[server]:[],fetchById:async()=>server,mutate:async()=>{throw Object.assign(new Error('stale'),{code:'PT409',status:409});}};
  await new V3SyncEngine({repository:f.repository,remote,featureEnabled:true,signalsSyncEnabled:true,locks:null}).syncOnce();assert.equal((await f.service.list())[0].status,'open');assert.equal((await f.service.history()).length,1);assert.equal((await f.repository.get('football_sessions',f.local.id)).rpe,7);f.repository.close();
});
test('panel renders hostile text literally and never resolves without confirmation',async()=>{
  class Element{
    constructor(tag){this.tag=tag;this.children=[];this.textContent='';this.attributes={};}
    append(...children){this.children.push(...children);}
    replaceChildren(...children){this.children=children;}
    setAttribute(key,value){this.attributes[key]=value;}
    focus(){this.focused=true;}
    set innerHTML(value){throw new Error(`Unsafe HTML: ${value}`);}
  }
  const old=globalThis.document;globalThis.document={createElement:tag=>new Element(tag)};
  try{
    const f=await fixture(),root=new Element('section');f.view.local.notes='<img src=x onerror=alert(1)>';
    let calls=0;const ui=new V3ConflictUI({root,service:{list:async()=>[f.view],resolve:async()=>{calls++;f.view.status='resolved';}},onClose:()=>{}});await ui.mount();
    const all=element=>[element,...element.children.flatMap(all)],nodes=all(root);assert.equal(calls,0);assert.ok(nodes.some(node=>node.tag==='pre'&&node.textContent.includes('<img src=x onerror=alert(1)>')));assert.ok(nodes.some(node=>node.tag==='label'));assert.ok(nodes.some(node=>node.tag==='summary'));await nodes.find(node=>node.textContent==='Confirmar decisión').onclick();assert.equal(calls,1);assert.ok(nodes.some(node=>node.textContent==='0 conflictos abiertos · 0 decisiones pendientes de sync · 1 resueltos'));assert.ok(nodes.find(node=>node.tag==='summary').focused);ui.destroy();
    f.view.status='open';const failing=new V3ConflictUI({root,service:{list:async()=>[f.view],resolve:async()=>{throw new Error('Affected active session');}},onClose:()=>{}});await failing.mount();const retry=all(root).find(node=>node.textContent==='Confirmar decisión');await retry.onclick();assert.equal(retry.disabled,false);assert.equal(retry.focused,true);assert.ok(all(root).some(node=>node.textContent.includes('Este conflicto afecta la sesión activa')));failing.destroy();f.repository.close();
  }finally{globalThis.document=old;}
});
test('archived operations cannot contaminate failed/retry entity status',async()=>{const f=await fixture(),decision=await f.service.resolve(f.view,'keep_local'),id=decision.operation_ids[0];await f.repository.setOperationStatus(id,'failed');assert.equal((await f.repository.get('football_sessions',f.local.id)).sync_status,'failed');await f.repository.retryOperation(id);assert.equal((await f.repository.get('football_sessions',f.local.id)).sync_status,'pending');f.repository.close();});
test('updated remote snapshot rejects stale decision and preserves audit-free state',async()=>{const f=await fixture();await f.repository.recordConflict({entity:'football_sessions',recordId:f.local.id,reason:'remote_version_conflict',remotePayload:{...f.remote,version:8}});await assert.rejects(f.service.resolve(f.view,'accept_remote'),/Conflict changed/);assert.equal((await f.service.history()).length,0);f.repository.close();});
test('ambiguous source review cannot be bypassed by a refreshed remote snapshot',async()=>{const f=await fixture();await f.repository.update('football_sessions',f.local.id,{migration_status:'pending_review'});const view=(await f.service.list())[0];assert.deepEqual(view.strategies,['defer']);await assert.rejects(f.service.resolve(view,'keep_local'));f.repository.close();});
test('remote version guard rejects changes sharing the same millisecond timestamp',async()=>{const f=await fixture(),transaction=f.repository.database.transaction(INTERNAL_STORES.conflicts,'readwrite'),done=transactionDone(transaction),store=transaction.objectStore(INTERNAL_STORES.conflicts),conflict=await requestResult(store.get(f.view.conflict_id));conflict.remote_payload.version=8;await requestResult(store.put(conflict));await done;assert.equal((await f.service.list())[0].updated_at,f.view.updated_at);await assert.rejects(f.service.resolve(f.view,'accept_remote'),/Conflict changed/);assert.equal((await f.service.history()).length,0);f.repository.close();});
