import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {IDBFactory} from 'fake-indexeddb';
import {V3LocalRepository} from '../js/v3/repository.js';
import {V3SyncEngine} from '../js/v3/sync-engine.js';
import {V3ConflictService} from '../js/v3/conflict-service.js';
import {V3ObservabilityService,v3FlagState} from '../js/v3/observability-service.js';
import {V3AuditService,resolutionAuditEvent} from '../js/v3/audit-service.js';
import {remotePayloadForOperation} from '../js/v3/sync-protocol.js';
import {withV3SyncLock} from '../js/v3/sync-lock.js';
import {safeDiagnosticError} from '../js/v3/diagnostic-model.js';
import {configureV3Observability} from '../js/v3/observability-runtime.js';
import {SupabaseV3Adapter} from '../js/v3/supabase-v3-adapter.js';
import {V3ObservabilityUI} from '../js/v3/observability-ui.js';
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',B='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const flags={getItem:key=>['nicoFit.v3.sync.enabled','v3.audit.enabled'].includes(key)?'true':null};
async function open(db=new IDBFactory(),userId=A){return V3LocalRepository.open({indexedDB:db,userId,featureEnabled:true});}
class Remote{
  constructor(){this.tables={};this.failure=null;this.authFailure=false;}
  async authenticatedUserId(){if(this.authFailure)throw Object.assign(new Error('token SECRET_TOKEN user@email.invalid'),{status:401,code:'PGRST301'});return A;}
  async fetchChanges(entity,{cursor}){return Object.values(this.tables[entity]||{}).filter(row=>!cursor||row.updated_at>cursor.updatedAt);}
  async fetchById(entity,id){return this.tables[entity]?.[id]||null;}
  async mutate(op,userId){if(this.failure)throw this.failure;const row={...remotePayloadForOperation(op,userId),updated_at:new Date().toISOString()};this.tables[op.entity]??={};this.tables[op.entity][row.id]=row;return row;}
}
const session=repository=>repository.create('workout_sessions',{session_date:'2026-09-15',label:'PRIVATE_NOTES'});
test('Supabase missing session with SDK status 400 is classified as auth, not permanent',async()=>{const adapter=new SupabaseV3Adapter({client:{auth:{getUser:async()=>({data:null,error:{name:'AuthSessionMissingError',status:400}})}}});await assert.rejects(adapter.authenticatedUserId(),error=>error.status===401&&error.code==='PGRST301');});
function service(repository,remote=new Remote(),extra={}){const engine=new V3SyncEngine({repository,remote,featureEnabled:true,locks:null,...extra});return new V3ObservabilityService({repository,engine,flagStorage:flags,locks:null,...extra});}
test('queue counts and approximate size do not expose operation payloads',async()=>{const repository=await open();await session(repository);const state=await service(repository).snapshot();assert.equal(state.operations.pending,1);assert.ok(state.queue.approximateBytes>0);assert.ok(!JSON.stringify(state).includes('PRIVATE_NOTES'));repository.close();});
test('successful sync persists attempt phases, confirmation and checkpoint across reload',async()=>{const db=new IDBFactory(),repository=await open(db),diagnostics=service(repository);await session(repository);await diagnostics.syncNow();let state=await diagnostics.snapshot();assert.ok(state.lastSuccessfulSyncAt);assert.equal(state.lastAttempt.status,'completed');assert.equal(state.operations.synced,1);await diagnostics.syncNow();assert.ok((await diagnostics.snapshot()).checkpoints.workout_sessions);repository.close();const reopened=await open(db);state=await service(reopened).snapshot();assert.ok(state.lastSuccessfulSyncAt);reopened.close();});
test('push network error exposes sanitized error and backoff, never counts as successful',async()=>{const repository=await open(),remote=new Remote();remote.failure=new TypeError('SECRET_TOKEN user@email.invalid');const diagnostics=service(repository,remote);await session(repository);await diagnostics.syncNow();const state=await diagnostics.snapshot();assert.equal(state.operations.failed,1);assert.equal(state.backoff.active,true);assert.equal(state.lastSuccessfulSyncAt,null);assert.equal(state.lastError.kind,'transient');assert.ok(!JSON.stringify(state).includes('SECRET_TOKEN'));assert.equal(state.actions.retryFailed,false);repository.close();});
test('retry due failed operations obeys backoff and uses existing atomic queue recovery',async()=>{const repository=await open(),remote=new Remote(),row=await session(repository);const [op]=await repository.listOperations();await repository.setOperationStatus(op.operation_id,'failed',{nextAttemptAt:new Date(Date.now()-1000).toISOString()});const diagnostics=service(repository,remote);assert.equal((await diagnostics.snapshot()).actions.retryFailed,true);await diagnostics.retryFailed();assert.equal((await repository.get('workout_sessions',row.id)).sync_status,'synced');repository.close();});
test('pull failure records error phase and preserves previous successful sync',async()=>{const repository=await open(),remote=new Remote(),diagnostics=service(repository,remote);await diagnostics.syncNow();const previous=(await diagnostics.snapshot()).lastSuccessfulSyncAt;remote.fetchChanges=async()=>{throw new TypeError('SECRET_PAYLOAD');};await assert.rejects(diagnostics.syncNow());const state=await diagnostics.snapshot();assert.equal(state.lastError.phase,'pull');assert.equal(state.lastSuccessfulSyncAt,previous);assert.equal(state.lastAttempt.status,'failed');repository.close();});
test('expired session recorded as auth failure without sending queue or exposing credentials',async()=>{const repository=await open(),remote=new Remote(),diagnostics=service(repository,remote);await session(repository);remote.authFailure=true;await assert.rejects(diagnostics.syncNow());const state=await diagnostics.snapshot();assert.equal(state.lastError.kind,'auth');assert.equal(state.operations.pending,1);assert.ok(!JSON.stringify(state).includes('user@email'));repository.close();});
test('offline attempt skips remote and online state updates independently',async()=>{const repository=await open();let online=false;const diagnostics=service(repository,new Remote(),{online:()=>online});assert.equal((await diagnostics.syncNow()).skipped,'offline');assert.equal((await diagnostics.snapshot()).lastAttempt.status,'offline');online=true;assert.equal((await diagnostics.snapshot()).online,true);await diagnostics.syncNow();assert.ok((await diagnostics.snapshot()).lastSuccessfulSyncAt);repository.close();});
test('lock snapshot omits tokens and two instances cannot run together',async()=>{const db=new IDBFactory(),one=await open(db),two=await open(db);let release,entered;const hold=new Promise(resolve=>release=resolve),ready=new Promise(resolve=>entered=resolve);const first=withV3SyncLock({repository:one,userId:A,locks:globalThis.navigator?.locks,task:async()=>{entered();await hold;}});await ready;const diagnostics=service(two);const state=await diagnostics.snapshot();assert.equal(state.lock.active,true);assert.ok(!JSON.stringify(state).includes('owner_token'));assert.equal((await diagnostics.syncNow()).skipped,'locked');release();await first;assert.equal((await diagnostics.snapshot()).lock.active,false);one.close();two.close();});
test('abandoned lease is reported expired and recovered by next sync',async()=>{const repository=await open();await repository.acquireLease(`nico-fit-v3-sync:${A}`,'PRIVATE_TOKEN',{now:1,ttlMs:1});const diagnostics=service(repository);assert.equal((await diagnostics.snapshot()).lock.expired,true);await diagnostics.syncNow();assert.equal((await diagnostics.snapshot()).lock.active,false);repository.close();});
test('conflict and recent resolution metadata omit notes and both snapshots',async()=>{const repository=await open(),row=await session(repository);await repository.recordConflict({entity:'workout_sessions',recordId:row.id,reason:'remote_version_conflict',remotePayload:{...row,user_id:A,version:2,notes:'SECRET_REMOTE'}});const diagnostics=service(repository);assert.equal((await diagnostics.snapshot()).openConflicts,1);const conflicts=new V3ConflictService({repository,locks:null}),view=(await conflicts.list())[0];await conflicts.resolve(view,'defer',{note:'SECRET_NOTE'});const state=await diagnostics.snapshot();assert.equal(state.recentResolutions[0].strategy,'defer');assert.ok(!JSON.stringify(state).includes('SECRET'));repository.close();});
test('user isolation includes telemetry, queue, resolutions, critical audits and runtime binding',async()=>{const db=new IDBFactory(),a=await open(db,A),b=await open(db,B);await session(a);await service(a).syncNow();const state=await new V3ObservabilityService({repository:b,flagStorage:flags}).snapshot();assert.equal(state.queue.operations,0);assert.equal(state.lastAttempt,null);assert.equal(state.recentResolutions.length,0);assert.equal((await b.auditEvents()).length,0);assert.throws(()=>new V3ObservabilityService({repository:b,engine:service(a).engine}));a.close();b.close();});
test('flags are safe booleans off by default; runtime rejects production or service-role client',()=>{assert.ok(Object.values(v3FlagState({getItem:()=>null})).every(value=>value===false));assert.equal(safeDiagnosticError({message:'SECRET',code:'SECRET_KEY'},'auth').code,null);assert.throws(()=>configureV3Observability({userId:A,engine:{repository:{userId:A},remote:{client:{supabaseUrl:'https://production.supabase.co'}}}}));assert.throws(()=>configureV3Observability({userId:A,engine:{repository:{userId:A},remote:{client:{supabaseUrl:'https://tmydirzzlmlmtjgwqcgh.supabase.co',supabaseKey:'sb_secret_private'}}}}));});
test('minimal audit keeps strategy, versions, user and time but no notes or payloads',()=>{const event=resolutionAuditEvent({id:A,entity:'football_sessions',record_id:B,strategy:'keep_local',local_revision:2,local_remote_version:3,remote_version:4,resolved_at:'2026-09-15T12:00:00Z',metadata:{note:'SECRET'},local_payload:{private:'SECRET'}},A);assert.equal(event.user_id,A);assert.equal(event.remote_version,4);assert.ok(!JSON.stringify(event).includes('SECRET'));});
test('audit retries interrupted delivery idempotently and defaults disabled',async()=>{const repository=await open();await repository.recordSyncAttempt(A,{startedAt:'2026-09-15T12:00:00Z',finishedAt:'2026-09-15T12:00:01Z',status:'failed',error:safeDiagnosticError({status:401},'auth')});const seen=new Set(),remote={authenticatedUserId:async()=>A,append:async event=>seen.add(event.event_id)},audit=new V3AuditService({repository,remote,flagStorage:flags,locks:null});await repository.setAuditDelivery(A,{status:'syncing',attempts:1});assert.equal((await audit.flush()).sent,1);assert.equal((await audit.flush()).sent,0);assert.equal(seen.size,1);const disabled=new V3AuditService({repository,remote,flagStorage:{getItem:()=>null}});assert.equal((await disabled.flush()).skipped,'disabled');repository.close();});
test('additive audit SQL is idempotent, owner-isolated and append-only in PostgreSQL',async()=>{const {PGlite}=await import('@electric-sql/pglite'),db=new PGlite();try{await db.exec(await readFile(new URL('../supabase/test-v3-local-bootstrap.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migration-v3-schema.sql',import.meta.url),'utf8'));const sql=await readFile(new URL('../supabase/migration-v3-observability.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);await db.exec(`insert into auth.users(id) values ('${A}'),('${B}'); set role authenticated; select set_config('request.jwt.claim.sub','${A}',false); insert into nico_fit_v3.operational_audit(event_id,user_id,event_type,error_kind,occurred_at,received_at) values ('${A}','${A}','sync_failure','auth',now(),'2000-01-01');`);assert.notEqual((await db.query('select received_at::text from nico_fit_v3.operational_audit')).rows[0].received_at.slice(0,4),'2000');await assert.rejects(db.exec(`insert into nico_fit_v3.operational_audit(event_id,user_id,event_type,error_kind,occurred_at) values ('${A}','${A}','sync_failure','auth',now());`),error=>error.code==='23505');await db.exec(`select set_config('request.jwt.claim.sub','${B}',false);`);assert.equal((await db.query('select * from nico_fit_v3.operational_audit')).rows.length,0);await assert.rejects(db.exec(`insert into nico_fit_v3.operational_audit(event_id,user_id,event_type,error_kind,occurred_at) values ('${B}','${A}','sync_failure','auth',now());`),error=>error.code==='42501');await assert.rejects(db.exec('delete from nico_fit_v3.operational_audit'),error=>error.code==='42501');await db.exec('reset role');await assert.rejects(db.exec('update nico_fit_v3.operational_audit set error_kind=\'permanent\''),error=>error.code==='55000');await db.exec('set role anon');await assert.rejects(db.exec('select * from nico_fit_v3.operational_audit'),error=>error.code==='42501');}finally{await db.close();}});
test('durable success survives retention and same-timestamp attempts use atomic sequence',async()=>{const repository=await open(),time='2026-09-15T12:00:00Z';await repository.recordSyncAttempt(A,{startedAt:time,finishedAt:time,status:'completed'});for(let i=0;i<35;i++)await repository.recordSyncAttempt(crypto.randomUUID(),{startedAt:time,finishedAt:time,status:'locked'});const state=await service(repository).snapshot();assert.equal(state.lastSuccessfulSyncAt,time.replace('Z','.000Z'));assert.equal(state.lastAttempt.status,'locked');assert.equal((await repository.operationalSnapshot()).attempts.length,30);repository.close();});
test('diagnostic quota failure does not prevent remote domain acknowledgement',async()=>{const repository=await open(),diagnostics=service(repository);await session(repository);repository.recordSyncAttempt=async()=>{throw new Error('QuotaExceededError');};const result=await diagnostics.syncNow();assert.equal(result.pushed,1);assert.equal((await repository.listOperations())[0].status,'synced');assert.equal((await diagnostics.snapshot()).lastSuccessfulSyncAt,null);repository.close();});
test('observability UI is read-only safe DOM, refresh preserves expansion, actions and network state',async()=>{class Element{constructor(tag){this.tag=tag;this.children=[];this.textContent='';}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}setAttribute(key,value){this[key]=value;}focus(){this.focused=true;}set innerHTML(value){throw new Error('Unsafe HTML');}}const prior=globalThis.document;globalThis.document={createElement:tag=>new Element(tag)};const repository=await open();try{await session(repository);const diagnostics=service(repository),root=new Element('section'),events=new EventTarget(),ui=new V3ObservabilityUI({root,service:diagnostics,onClose:()=>{},networkEvents:events});await ui.mount();const detail=root.children.find(node=>node.tag==='details');detail.open=true;await ui.sync.onclick();assert.equal(detail.open,true);assert.equal(ui.busy,false);assert.ok(!ui.technical.textContent.includes('PRIVATE_NOTES'));assert.ok(ui.facts.textContent.includes('Cola: 0'));assert.equal(ui.summary.role,'status');diagnostics.online=()=>false;await ui.refreshOnNetwork();assert.ok(ui.summary.textContent.includes('offline'));assert.equal(ui.sync.disabled,true);assert.equal(detail.open,true);ui.destroy();}finally{globalThis.document=prior;repository.close();}});
test('audit network backoff retains failed delivery and no infinite retries',async()=>{const repository=await open();await repository.recordSyncAttempt(A,{startedAt:'2026-09-15T12:00:00Z',finishedAt:'2026-09-15T12:00:01Z',status:'failed',error:safeDiagnosticError({status:401},'auth')});let calls=0;const audit=new V3AuditService({repository,flagStorage:flags,locks:null,remote:{authenticatedUserId:async()=>A,append:async()=>{calls++;throw new TypeError('SECRET');}}});assert.equal((await audit.flush()).failed,1);assert.equal((await audit.flush()).failed,0);assert.equal(calls,1);const snapshot=await audit.snapshot();assert.equal(snapshot.counts.failed,1);assert.ok(!JSON.stringify(snapshot).includes('SECRET'));repository.close();});
