import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {IDBFactory} from 'fake-indexeddb';
import {V3LocalRepository} from '../js/v3/repository.js';
import {V3RoutineService} from '../js/v3/routine-service.js';
import {V3TrainingEngine} from '../js/v3/training-engine.js';
import {V3SyncEngine} from '../js/v3/sync-engine.js';
import {V3ConflictService} from '../js/v3/conflict-service.js';
import {SupabaseV3Adapter} from '../js/v3/supabase-v3-adapter.js';
import {databaseNameForUser,requestResult,transactionDone} from '../js/v3/indexed-db.js';
import {routinePrescription} from '../js/v3/routine-validation.js';
import {routineIdentityCard,routineListView} from '../js/v3/routine-presentation.js';
import {importV2RoutineTrace} from '../js/v3/import-v2-routines.js';
import {isV3RoutinesEnabled,isV3RoutinesSyncEnabled,isV3TrainingEnabled,isV3SyncEnabled,isV3CoachEnabled} from '../js/v3/feature-flags.js';
import {remotePayloadForOperation} from '../js/v3/sync-protocol.js';
import {v3Progression} from '../js/v3/training-progression.js';
import {applyCoachRules} from '../js/v3/coach-rules.js';
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',B='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const rx={sets:3,min:8,max:12,measurement_kind:'reps',target_rir:0,rest:90,step:2.5,notes:'Prescripción original'};
async function open(db=new IDBFactory(),userId=A){return V3LocalRepository.open({indexedDB:db,userId,featureEnabled:true});}
async function setup(db=new IDBFactory()){
 const repository=await open(db),service=new V3RoutineService({repository,featureEnabled:true});
 const first=await repository.create('exercise_catalog',{stable_key:'one',canonical_name:'Primero',measurement_kind:'reps'}),second=await repository.create('exercise_catalog',{stable_key:'two',canonical_name:'Segundo',measurement_kind:'reps'});
 const exercises=[first,second].map(row=>({exercise_catalog_id:row.id,prescription_snapshot:rx}));
 const graph=await service.create({name:'Rutina base',exercises,dayIndex:2});
 const training=new V3TrainingEngine({repository,featureEnabled:true,routinesEnabled:true,now:()=>new Date('2026-09-15T12:00:00Z')});return {repository,service,graph,training,exercises};
}
class Remote{
 constructor(){this.tables={};this.calls=[];}
 async authenticatedUserId(){return A;}
 async fetchChanges(entity,{cursor,pageSize}){return Object.values(this.tables[entity]||{}).filter(row=>!cursor||row.updated_at>cursor.updatedAt||row.updated_at===cursor.updatedAt&&row.id>cursor.id).sort((a,b)=>a.updated_at.localeCompare(b.updated_at)||a.id.localeCompare(b.id)).slice(0,pageSize);}
 async fetchById(entity,id){return this.tables[entity]?.[id]||null;}
 async mutate(op,userId){this.calls.push(op.entity);const current=await this.fetchById(op.entity,op.record_id);if(current&&op.type!=='insert'&&current.version!==op.base_remote_version)throw Object.assign(new Error('version conflict'),{code:'PT409',status:409});const row={...remotePayloadForOperation(op,userId),updated_at:new Date().toISOString()};this.tables[op.entity]??={};this.tables[op.entity][row.id]=row;return row;}
}
test('routine flags default off and enable no other V3 features',()=>{const storage={getItem:key=>key==='v3.routines.enabled'?'true':null};assert.equal(isV3RoutinesEnabled({getItem:()=>null}),false);assert.equal(isV3RoutinesEnabled(storage),true);for(const fn of [isV3RoutinesSyncEnabled,isV3TrainingEnabled,isV3SyncEnabled,isV3CoachEnabled])assert.equal(fn(storage),false);});
test('IndexedDB version 3 upgrades preserve historical session and active checkpoint',async()=>{const db=new IDBFactory(),request=db.open(databaseNameForUser(A),3);request.onupgradeneeded=()=>{request.result.createObjectStore('workout_sessions',{keyPath:'id'});request.result.createObjectStore('sync_metadata',{keyPath:'key'});};const old=await requestResult(request),transaction=old.transaction(['workout_sessions','sync_metadata'],'readwrite'),done=transactionDone(transaction);transaction.objectStore('workout_sessions').put({id:A,owner_id:A,session_date:'2026-09-15',status:'draft',notes:'unchanged'});transaction.objectStore('sync_metadata').put({key:'training:state',owner_id:A,value:{activeSessionId:A}});await done;old.close();const repository=await open(db);assert.equal(repository.database.version,4);assert.equal((await repository.getTrainingState()).activeSessionId,A);assert.equal((await repository.get('workout_sessions',A)).notes,'unchanged');assert.equal((await repository.listRecords('routine_templates')).length,0);repository.close();});
test('create routine graph, UUID identity and explicit ordered prescription',async()=>{const {repository,graph}=await setup();assert.match(graph.template.id,/^[0-9a-f-]{36}$/);assert.equal(graph.version.version_number,1);assert.deepEqual(graph.exercises.map(row=>row.position),[0,1]);assert.equal(graph.snapshot.exercises[0].prescription_snapshot.target_rir,0);repository.close();});
test('new version and rename leave started session and historical snapshots intact after reload',async()=>{const db=new IDBFactory(),{repository,service,graph,training,exercises}=await setup(db);const session=await training.createSession({routineVersionId:graph.version.id});const before=structuredClone(session);await service.rename(graph.template.id,'Nombre nuevo');await service.createVersion(graph.template.id,{exercises:exercises.map(ex=>({...ex,prescription_snapshot:{...rx,sets:5}}))});assert.deepEqual((await training.snapshot()).session.routine_snapshot,before.session.routine_snapshot);assert.equal((await service.version(graph.version.id)).snapshot.name,'Rutina base');repository.close();const reopened=await open(db),engine=new V3TrainingEngine({repository:reopened,featureEnabled:true,routinesEnabled:true});await engine.recover();assert.equal((await engine.snapshot()).session.routine_version,1);assert.deepEqual((await engine.snapshot()).session.routine_snapshot,before.session.routine_snapshot);reopened.close();});
test('duplicate creates independent template/version/occurrences and activation is nondestructive',async()=>{const {repository,service,graph,training}=await setup();const copied=await service.duplicate(graph.version.id,'Variante');assert.notEqual(copied.template.id,graph.template.id);assert.equal(copied.template.derived_from_routine_id,graph.template.id);assert.notEqual(copied.exercises[0].id,graph.exercises[0].id);assert.deepEqual(copied.exercises.map(row=>row.prescription_snapshot),graph.exercises.map(row=>row.prescription_snapshot));await training.createSession({routineVersionId:graph.version.id});await service.setActive(graph.template.id,false);await assert.rejects(training.createSession({routineVersionId:graph.version.id}),/desactivada/);assert.equal((await training.snapshot()).session.routine_version,1);assert.equal((await service.version(graph.version.id)).version.deleted_at,null);await service.setActive(graph.template.id,true);assert.equal((await service.list()).length,2);repository.close();});
test('reorder and repeated exercises publish a new version without editing old occurrences',async()=>{const {repository,service,graph}=await setup();const input=[graph.snapshot.exercises[1],graph.snapshot.exercises[0],graph.snapshot.exercises[0]],next=await service.createVersion(graph.template.id,{exercises:input});assert.equal(next.version.version_number,2);assert.deepEqual(next.exercises.map(row=>row.exercise_catalog_id),input.map(row=>row.exercise_catalog_id));assert.equal(new Set(next.exercises.map(row=>row.id)).size,3);assert.equal((await service.version(graph.version.id)).exercises[0].exercise_catalog_id,graph.exercises[0].exercise_catalog_id);repository.close();});
test('published version, occurrence and session identity cannot be edited through repository',async()=>{const {repository,graph,training}=await setup();await assert.rejects(repository.update('routine_versions',graph.version.id,{name_snapshot:'Alterado'}),/inmutable/);await assert.rejects(repository.update('routine_exercises',graph.exercises[0].id,{position:4}),/inmutable/);const session=await training.createSession({routineVersionId:graph.version.id});await assert.rejects(repository.update('workout_sessions',session.session.id,{routine_version:2}),/inmutable/);repository.close();});
test('two local publishers cannot assign the same routine version number',async()=>{const {repository,service,graph,exercises}=await setup();let arrived=0,release;const gate=new Promise(resolve=>release=resolve),commit=repository.commitLocalChanges.bind(repository);repository.commitLocalChanges=async(...args)=>{if(args[0][0]?.entity==='routine_versions'){if(++arrived===2)release();await gate;}return commit(...args);};const results=await Promise.allSettled([service.createVersion(graph.template.id,{exercises}),service.createVersion(graph.template.id,{exercises})]);assert.equal(results.filter(row=>row.status==='fulfilled').length,1);assert.equal((await repository.listRecords('routine_versions')).length,2);assert.equal((await repository.listRecords('routine_exercises')).length,4);repository.close();});
test('seeding reuses V2 imported stable catalog IDs without renaming or changing units',async()=>{const repository=await open(),imported=await repository.create('exercise_catalog',{stable_key:'sentadilla-prensa',canonical_name:'Nombre importado',measurement_kind:'mixed'}),service=new V3RoutineService({repository,featureEnabled:true});const defaults=await service.seedDefaults();assert.equal(defaults[0].exercises[0].exercise_catalog_id,imported.id);assert.equal(defaults[0].exercises[0].exercise_name_snapshot,'Sentadilla o prensa');assert.equal((await repository.get('exercise_catalog',imported.id)).measurement_kind,'mixed');assert.equal((await repository.listRecords('exercise_catalog')).filter(row=>row.stable_key==='sentadilla-prensa').length,1);repository.close();});
test('same visible V2 name with different stable keys never merges catalog identities',async()=>{const repository=await open(),one=await repository.create('exercise_catalog',{stable_key:'legacy:a',canonical_name:'Remo',measurement_kind:'reps'}),two=await repository.create('exercise_catalog',{stable_key:'legacy:b',canonical_name:'Remo',measurement_kind:'reps'}),service=new V3RoutineService({repository,featureEnabled:true}),routine=await service.create({name:'Identidad explícita',exercises:[one,two].map(row=>({exercise_catalog_id:row.id,prescription_snapshot:rx}))});assert.deepEqual(routine.exercises.map(row=>row.exercise_catalog_id),[one.id,two.id]);assert.equal((await repository.listRecords('exercise_catalog')).filter(row=>row.canonical_name==='Remo').length,2);repository.close();});
test('duplicate ordinal from Supabase is persisted as conflict and is not renumbered silently',async()=>{const {repository,service,graph,exercises}=await setup(),remote=new Remote(),engine=new V3SyncEngine({repository,remote,featureEnabled:true,routinesSyncEnabled:true,locks:null});await engine.syncOnce();const next=await service.createVersion(graph.template.id,{exercises});const query={insert:()=>({select:()=>({single:async()=>({error:{code:'23505',message:'duplicate'},status:409})})})},adapter=new SupabaseV3Adapter({client:{schema:()=>({from:()=>query})}}),op=(await repository.listOperations({status:'pending'})).find(row=>row.entity==='routine_versions');await assert.rejects(adapter.mutate(op,A),error=>error.code==='PT409'&&error.reason==='routine_version_number_collision');const mutate=remote.mutate.bind(remote);remote.mutate=async(operation,userId)=>operation.entity==='routine_versions'?adapter.mutate(operation,userId):mutate(operation,userId);await engine.syncOnce();const view=(await new V3ConflictService({repository,locks:null}).list())[0];assert.equal(view.origin,'routine_version_number_collision');assert.deepEqual(view.strategies,['defer']);assert.equal((await repository.get('routine_versions',next.version.id)).version_number,2);repository.close();});
test('remote ordinal winner is recorded before IndexedDB unique index can reject it',async()=>{const {repository,service,graph,exercises}=await setup(),remote=new Remote(),engine=new V3SyncEngine({repository,remote,featureEnabled:true,routinesSyncEnabled:true,locks:null});await engine.syncOnce();const loser=await service.createVersion(graph.template.id,{exercises}),winnerId=crypto.randomUUID(),stamp='2099-01-01T00:00:00.000Z';remote.tables.routine_versions[winnerId]={...loser.version,id:winnerId,user_id:A,version:1,created_at:stamp,updated_at:stamp};delete remote.tables.routine_versions[winnerId].owner_id;delete remote.tables.routine_versions[winnerId].remote_version;delete remote.tables.routine_versions[winnerId].local_revision;delete remote.tables.routine_versions[winnerId].sync_status;const result=await engine.syncOnce();assert.ok(result.conflicts>=1);const conflict=(await new V3ConflictService({repository,locks:null}).list()).find(row=>row.record_id===loser.version.id);assert.equal(conflict.origin,'routine_version_number_collision');assert.equal(conflict.remote.version,1);assert.equal(await repository.get('routine_versions',winnerId),null);repository.close();});
test('explicit null versus zero, reps versus seconds and invalid prescriptions',()=>{assert.equal(routinePrescription({...rx,step:null,target_rir:null,rest:null}).step,null);assert.equal(routinePrescription({...rx,step:0,target_rir:0,rest:0}).step,0);assert.equal(routinePrescription({...rx,measurement_kind:'seconds',min:30,max:45}).measurement_kind,'seconds');for(const input of [{...rx,target_rir:8},{...rx,rest:-1},{...rx,min:null},{...rx,sets:null},{...rx,min:20,max:10},{...rx,measurement_kind:'mixed'}])assert.throws(()=>routinePrescription(input));});
test('default Tuesday/Thursday/Friday mapping is deterministic and idempotent across reload/users',async()=>{const db=new IDBFactory(),repository=await open(db),service=new V3RoutineService({repository,featureEnabled:true});const first=await service.seedDefaults(),count=(await repository.listOperations()).length;await service.seedDefaults();assert.equal((await repository.listOperations()).length,count);assert.deepEqual(first.map(row=>row.version.day_index),[2,4,5]);repository.close();const reopened=await open(db),second=await new V3RoutineService({repository:reopened,featureEnabled:true}).seedDefaults();assert.deepEqual(second.map(row=>row.template.id),first.map(row=>row.template.id));const other=await open(db,B),third=await new V3RoutineService({repository:other,featureEnabled:true}).seedDefaults();assert.notEqual(third[0].template.id,first[0].template.id);assert.equal(await other.get('routine_templates',first[0].template.id),null);reopened.close();other.close();});
test('controlled legacy trace preserves sessions and marks ambiguous prescriptions pending review',async()=>{const repository=await open(),legacyEngine=new V3TrainingEngine({repository,featureEnabled:true,routinesEnabled:false,now:()=>new Date('2026-09-15T12:00:00Z')}),session=await legacyEngine.createSession({dayIndex:2}),service=new V3RoutineService({repository,featureEnabled:true});const ambiguous=structuredClone(session);ambiguous.session.id='ambiguous';ambiguous.exercises[0].prescription_snapshot.sets=99;const before=await repository.get('workout_sessions',session.session.id);const rows=await importV2RoutineTrace({service,sessions:[session,ambiguous]});assert.equal(rows[0].migration_status,'migrated');assert.equal(rows[1].migration_status,'pending_review');assert.equal(rows[1].target_id,null);const again=await importV2RoutineTrace({service,sessions:[session,ambiguous]});assert.equal(again[0].created,false);assert.deepEqual(await repository.get('workout_sessions',session.session.id),before);repository.close();});
test('historical exercise without catalog identity remains readable after staging download',async()=>{const repository=await open(),session=await repository.create('workout_sessions',{session_date:'2026-09-15',status:'completed',started_at:'2026-09-15T12:00:00Z',ended_at:'2026-09-15T13:00:00Z',label:'Histórica'});await repository.create('session_exercises',{session_id:session.id,exercise_catalog_id:null,position:0,exercise_name_snapshot:'Ejercicio histórico',prescription_snapshot:rx,notes:''});const engine=new V3TrainingEngine({repository,featureEnabled:true,routinesEnabled:true});const snapshot=await engine.snapshot(session.id);assert.equal(snapshot.exercises[0].catalog,null);assert.equal(snapshot.exercises[0].exercise_name_snapshot,'Ejercicio histórico');repository.close();});
test('sync explicit routine graph before session and paginate back into another isolated device',async()=>{const {repository,graph,training}=await setup(),remote=new Remote();const session=await training.createSession({routineVersionId:graph.version.id});const engine=new V3SyncEngine({repository,remote,featureEnabled:true,routinesSyncEnabled:true,locks:null,pageSize:1});assert.equal((await engine.syncOnce()).failed,0);assert.ok(remote.calls.indexOf('routine_versions')<remote.calls.indexOf('workout_sessions'));const other=await open(),download=new V3SyncEngine({repository:other,remote,featureEnabled:true,routinesSyncEnabled:true,locks:null,pageSize:1});await download.syncOnce();assert.deepEqual((await other.get('workout_sessions',session.session.id)).routine_snapshot,session.session.routine_snapshot);assert.equal((await new V3RoutineService({repository:other,featureEnabled:true}).version(graph.version.id,{forTraining:true})).exercises.length,2);assert.equal((await repository.listOperations()).every(row=>row.status==='synced'),true);repository.close();other.close();});
test('routine sync flag off never strips prescription or sends routine-linked session graph',async()=>{const {repository,graph,training}=await setup(),remote=new Remote();await training.createSession({routineVersionId:graph.version.id});const engine=new V3SyncEngine({repository,remote,featureEnabled:true,routinesSyncEnabled:false,locks:null});await engine.syncOnce();assert.deepEqual(remote.calls,['exercise_catalog','exercise_catalog']);assert.ok((await repository.listOperations({status:'pending'})).some(row=>row.entity==='workout_sessions'));repository.close();});
test('template version conflict is visible while active session remains unchanged and usable',async()=>{const {repository,service,graph,training}=await setup(),session=await training.createSession({routineVersionId:graph.version.id}),remote=new Remote(),sync=new V3SyncEngine({repository,remote,featureEnabled:true,routinesSyncEnabled:true,locks:null});await sync.syncOnce();await service.rename(graph.template.id,'Local');const server=remote.tables.routine_templates[graph.template.id];server.name='Remoto';server.version=2;server.updated_at='2099-01-01T00:00:00Z';await sync.syncOnce();const conflicts=await new V3ConflictService({repository,locks:null}).list();assert.equal(conflicts[0].entity,'routine_templates');assert.ok((await training.snapshot()).conflicts.length);assert.deepEqual((await training.snapshot()).session.routine_snapshot,session.session.routine_snapshot);await training.saveSet(session.exercises[0].id,{load_kg:10,reps:10,rir:0,is_completed:true});assert.equal((await training.snapshot()).exercises[0].sets.length,1);await assert.rejects(training.createSession({routineVersionId:graph.version.id}),/Conflicto/);repository.close();});
test('catalog conflict is surfaced through the routine graph and blocks new sessions',async()=>{const {repository,service,graph,training}=await setup(),catalog=await repository.get('exercise_catalog',graph.exercises[0].exercise_catalog_id);await repository.recordConflict({entity:'exercise_catalog',recordId:catalog.id,reason:'remote_version_conflict',localPayload:catalog,remotePayload:{...catalog,owner_user_id:A,version:1}});const row=(await service.list()).find(item=>item.id===graph.template.id);assert.equal(row.conflicts[0].record_id,catalog.id);await assert.rejects(training.createSession({routineVersionId:graph.version.id}),/Catálogo|Conflicto/);repository.close();});
test('coach and progression use historical version, never current template or different version history',async()=>{const {repository,service,graph,training,exercises}=await setup(),current=await training.createSession({routineVersionId:graph.version.id}),next=await service.createVersion(graph.template.id,{exercises:exercises.map(ex=>({...ex,prescription_snapshot:{...rx,sets:1}}))});const previous=structuredClone(current);previous.session={...previous.session,id:crypto.randomUUID(),routine_version:next.version.version_number,status:'completed',session_date:'2026-09-08',started_at:'2026-09-08T12:00:00Z',rpe:6};previous.exercises[0].sets=Array.from({length:3},()=>({load_kg:20,reps:12,rir:3,is_completed:true}));const result=v3Progression({exercise:current.exercises[0],session:current.session,history:[previous],now:new Date('2026-09-15T12:00:00Z'),readinessScore:90});assert.equal(result.kg,'');const signals={readinessScore:90,pain:0,freshness:5,sleep:5,energy:5,daysToMatch:4,dayIndex:2,footballTrend:{changePercent:0},gymTrend:{changePercent:0},warnings:[],patterns:[],history:[previous]};const coach=applyCoachRules(signals,current);assert.equal(coach.exerciseAdjustments[0].suggestedSets,3);assert.ok(coach.warnings.some(text=>text.includes('Sin sesión anterior')));repository.close();});
test('routine read-only view uses safe DOM and identifies version and active state',()=>{class Node{constructor(tag){this.tag=tag;this.children=[];}append(...items){this.children.push(...items);}setAttribute(key,value){this[key]=value;}set innerHTML(value){throw new Error('unsafe');}}const prior=globalThis.document;globalThis.document={createElement:tag=>new Node(tag)};try{const card=routineIdentityCard({routine_id:A,routine_version:1,name:'<img onerror=x>',exercises:[]},{state:'inactive'});assert.equal(card.children[1].textContent,'<img onerror=x> · versión 1');assert.equal(card.children[3].textContent,'Estado del template: inactive');assert.equal(routineListView([{name:'Rutina',is_active:false,id:A,conflicts:[],versions:[{version_number:2}]}]).children[1].children[0].textContent.includes('inactiva'),true);}finally{globalThis.document=prior;}});
test('additive routine SQL is idempotent with RLS, optimistic versions, immutable history and tombstones',async()=>{
 const {PGlite}=await import('@electric-sql/pglite'),db=new PGlite();const {repository,graph,training}=await setup();const session=await training.createSession({routineVersionId:graph.version.id});
 try{await db.exec(await read('supabase/test-v3-local-bootstrap.sql'));await db.exec(await read('supabase/migration-v3-schema.sql'));const migration=await read('supabase/migration-v3-routines.sql');await db.exec(migration);await db.exec(migration);await db.exec('create role authenticator nologin');await db.exec(await read('supabase/staging-v3-api-grants.sql'));await db.exec(await read('supabase/staging-v3-routines-api-grants.sql'));await db.exec(`insert into auth.users(id) values ('${A}'),('${B}');set role authenticated;select set_config('request.jwt.claim.sub','${A}',false);`);
 const operations=await repository.listOperations();for(const op of operations){const payload=remotePayloadForOperation(op,A),keys=Object.keys(payload),values=keys.map(key=>payload[key]);await db.query(`insert into nico_fit_v3.${op.entity}(${keys.join(',')}) values (${keys.map((_,index)=>'$'+(index+1)).join(',')})`,values.map(value=>value&&typeof value==='object'?JSON.stringify(value):value));}
 await assert.rejects(db.exec(`update nico_fit_v3.routine_templates set name='stale',version=1 where id='${graph.template.id}'`),error=>error.code==='PT409');await db.exec(`update nico_fit_v3.routine_templates set name='Renamed',is_active=false,version=2 where id='${graph.template.id}'`);
 assert.deepEqual((await db.query(`select routine_snapshot from nico_fit_v3.workout_sessions where id='${session.session.id}'`)).rows[0].routine_snapshot,session.session.routine_snapshot);
 await assert.rejects(db.exec(`update nico_fit_v3.routine_versions set name_snapshot='Mutated',version=2 where id='${graph.version.id}'`),error=>error.code==='PT409');await assert.rejects(db.exec(`update nico_fit_v3.workout_sessions set routine_version=2,version=2 where id='${session.session.id}'`),error=>error.code==='PT409');
 await db.exec(`select set_config('request.jwt.claim.sub','${B}',false);`);assert.equal((await db.query('select * from nico_fit_v3.routine_versions')).rows.length,0);await assert.rejects(db.exec(`insert into nico_fit_v3.routine_templates(id,user_id,stable_key,name) values ('${B}','${A}','cross','Cross')`),error=>error.code==='42501');await db.exec(`select set_config('request.jwt.claim.sub','${A}',false);update nico_fit_v3.routine_templates set deleted_at=now(),version=3 where id='${graph.template.id}'`);await assert.rejects(db.exec(`update nico_fit_v3.routine_templates set deleted_at=null,version=4 where id='${graph.template.id}'`),error=>error.code==='55000');await assert.rejects(db.exec('delete from nico_fit_v3.routine_templates'),error=>error.code==='42501');await db.exec('set role anon');await assert.rejects(db.exec('select * from nico_fit_v3.routine_templates'),error=>error.code==='42501');
 }finally{await db.close();repository.close();}
});
