import test from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory} from 'fake-indexeddb';
import {readFile} from 'node:fs/promises';
import {V3LocalRepository} from '../js/v3/repository.js';
import {V3SignalsRepository} from '../js/v3/signals-repository.js';
import {importV2Signals} from '../js/v3/import-v2-signals.js';
import {V3SyncEngine} from '../js/v3/sync-engine.js';
import {remotePayloadForOperation} from '../js/v3/sync-protocol.js';
import {ENTITY_STORES,databaseNameForUser,requestResult,transactionDone} from '../js/v3/indexed-db.js';
import {isV3SignalsEnabled,isV3SignalsSyncEnabled} from '../js/v3/feature-flags.js';
import {V3CoachService} from '../js/v3/coach-service.js';
import {validateSignal} from '../js/v3/signals-validation.js';

const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',B='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',date='2026-09-15';
const readiness={local_date:date,sleep:5,energy:5,freshness:5,pain:0};
const football={local_date:date,session_type:'training',duration_minutes:90,rpe:9,minutes_played:0};
async function open(indexedDB=new IDBFactory(),userId=A){const repository=await V3LocalRepository.open({indexedDB,userId,featureEnabled:true});return new V3SignalsRepository({repository,featureEnabled:true});}
class Remote{
  constructor(){this.tables=Object.fromEntries(ENTITY_STORES.map(name=>[name,new Map()]));this.tick=0;this.calls=[];}
  async authenticatedUserId(){return A;}
  async fetchChanges(entity,{cursor,pageSize}){this.calls.push(entity);return [...this.tables[entity].values()].filter(row=>!cursor||row.updated_at>cursor.updatedAt||row.updated_at===cursor.updatedAt&&row.id>cursor.id).sort((a,b)=>a.updated_at.localeCompare(b.updated_at)||a.id.localeCompare(b.id)).slice(0,pageSize);}
  async fetchById(entity,id){return this.tables[entity].get(id)??null;}
  async mutate(operation,userId){const table=this.tables[operation.entity],old=table.get(operation.record_id),payload=remotePayloadForOperation(operation,userId);if(old&&(old.deleted_at||payload.version!==old.version+1))throw Object.assign(new Error('stale'),{code:'PT409',status:409});const timestamp=new Date(Date.UTC(2026,8,15,0,0,++this.tick)).toISOString(),record={...old,...payload,updated_at:timestamp,created_at:old?.created_at??payload.created_at,deleted_at:payload.deleted_at??null};if(operation.entity==='football_sessions')record.calculated_load=record.duration_minutes*record.rpe;table.set(record.id,record);return structuredClone(record);}
}
const sync=(signals,remote,extra={})=>new V3SyncEngine({repository:signals.repository,remote,featureEnabled:true,signalsSyncEnabled:true,locks:null,...extra});

test('readiness persists offline after reload with stable UUID and revision edits',async()=>{const db=new IDBFactory(),signals=await open(db),row=await signals.save('daily_readiness',readiness);assert.equal(row.sync_status,'pending');signals.repository.close();const reopened=await open(db);assert.equal((await reopened.list('daily_readiness'))[0].id,row.id);const edited=await reopened.save('daily_readiness',{...readiness,pain:4},{expectedLocalRevision:row.local_revision});assert.equal(edited.id,row.id);assert.equal(edited.local_revision,2);await assert.rejects(reopened.save('daily_readiness',readiness),/revision/);reopened.repository.close();});
test('multiple same-day football sessions preserve zero and null minutes distinctly',async()=>{const signals=await open();const first=await signals.save('football_sessions',football),second=await signals.save('football_sessions',{...football,minutes_played:null});assert.notEqual(first.id,second.id);assert.equal(first.minutes_played,0);assert.equal(second.minutes_played,null);assert.equal(first.calculated_load,810);assert.equal((await signals.list('football_sessions',{date})).length,2);signals.repository.close();});
test('match review links to owned match and rejects training or wrong date',async()=>{const signals=await open(),match=await signals.save('football_sessions',{...football,session_type:'match'}),input={local_date:date,football_session_id:match.id,energy:4,legs:3,performance:4,rpe:null,minutes_played:0};const review=await signals.save('match_reviews',input);assert.equal(review.rpe,null);const training=await signals.save('football_sessions',football);await assert.rejects(signals.save('match_reviews',{...input,football_session_id:training.id}));await assert.rejects(signals.save('match_reviews',{...input,local_date:'2026-09-16'}));signals.repository.close();});
test('new signals sync later with server confirmation and versions',async()=>{const signals=await open(),remote=new Remote();const row=await signals.save('football_sessions',football);const result=await sync(signals,remote,{pageSize:1}).syncOnce();assert.equal(result.pushed,1);assert.equal((await signals.repository.get('football_sessions',row.id)).remote_version,1);await signals.save('football_sessions',{...football,rpe:8},{id:row.id,expectedLocalRevision:1});await sync(signals,remote).syncOnce();assert.equal((await signals.repository.get('football_sessions',row.id)).remote_version,2);signals.repository.close();});
test('remote change conflicts with local update and is never silently overwritten',async()=>{const signals=await open(),remote=new Remote(),row=await signals.save('daily_readiness',readiness);await sync(signals,remote).syncOnce();await signals.save('daily_readiness',{...readiness,pain:4},{expectedLocalRevision:1});const current=remote.tables.daily_readiness.get(row.id);remote.tables.daily_readiness.set(row.id,{...current,pain:7,version:2,updated_at:'2026-09-16T00:00:00Z'});const result=await sync(signals,remote).syncOnce();assert.equal(result.conflicts,1);assert.equal((await signals.repository.get('daily_readiness',row.id)).pain,4);const edited=await signals.save('daily_readiness',{...readiness,pain:5},{expectedLocalRevision:2});assert.equal(edited.sync_status,'conflict');signals.repository.close();});
test('soft deletion cascades linked reviews and prevents resurrection',async()=>{const signals=await open(),remote=new Remote(),row=await signals.save('football_sessions',{...football,session_type:'match'});const review=await signals.save('match_reviews',{local_date:date,football_session_id:row.id,energy:4,legs:4,performance:4});await sync(signals,remote).syncOnce();await signals.softDelete('football_sessions',row.id,1);await sync(signals,remote).syncOnce();assert.ok(remote.tables.football_sessions.get(row.id).deleted_at);assert.ok(remote.tables.match_reviews.get(review.id).deleted_at);await assert.rejects(signals.save('football_sessions',football,{id:row.id,expectedLocalRevision:2}),/deleted/);signals.repository.close();});
test('user databases and imported identities never mix',async()=>{const db=new IDBFactory(),a=await open(db,A),b=await open(db,B);const row=await a.save('daily_readiness',readiness);assert.equal((await b.list('daily_readiness')).length,0);assert.equal(await b.repository.get('daily_readiness',row.id),null);a.repository.close();b.repository.close();});
test('V2 import is atomic and idempotent with ambiguous reviews preserved in trace',async()=>{const signals=await open(),v2={readiness:[{date,sleep:5,energy:5,fatigue:1,pain:0}],football:[{date,type:'Partido',duration:90,rpe:8,minutes:90}],matches:[{date,energy:4,legs:4,performance:4}],tombstones:[]};assert.deepEqual(await importV2Signals(signals,v2),{migrated:2,pending_review:1,skipped:0});assert.deepEqual(await importV2Signals(signals,v2),{migrated:0,pending_review:0,skipped:0});const mappings=await signals.repository.listMigrationMappings();assert.ok(mappings.every(row=>row.source_payload));const row=(await signals.list('daily_readiness'))[0];const updated=await signals.save('daily_readiness',{...readiness,pain:2},{expectedLocalRevision:row.local_revision});assert.equal(updated.id,row.id);signals.repository.close();});
test('ambiguous duplicate values, unknown football type and tombstones are not inferred',async()=>{const signals=await open();const report=await importV2Signals(signals,{readiness:[{date,sleep:1},{date,sleep:5}],football:[{date,type:'unknown'}],matches:[{date,energy:4,legs:4,performance:4}],tombstones:[{entity:'matches',recordKey:date}]});assert.equal(report.pending_review,2);assert.equal(report.skipped,1);assert.equal((await signals.list('daily_readiness')).length,0);signals.repository.close();});
test('bridge enabled Coach uses V3 signals exclusively and exposes conflicts',async()=>{const signals=await open();await signals.save('daily_readiness',readiness);await signals.save('football_sessions',football);const old=globalThis.localStorage;globalThis.localStorage={getItem:key=>key==='v3.signals.enabled'?'true':null};try{const service=new V3CoachService({engine:{repository:signals.repository,history:async()=>[]},featureEnabled:true,now:()=>new Date(`${date}T12:00:00`)});let result=await service.today(null);assert.equal(result.signals.readinessScore,100);assert.equal(result.signals.intenseFootball,true);const row=(await signals.list('daily_readiness'))[0];await signals.repository.recordConflict({entity:'daily_readiness',recordId:row.id,operationIds:[],localPayload:row,remotePayload:{...row,pain:4},reason:'test'});result=await service.today(null);assert.equal(result.recommendation.readinessScore,null);assert.ok(result.recommendation.warnings.some(value=>value.includes('Conflictos')));}finally{globalThis.localStorage=old;signals.repository.close();}});
test('bridge and remote flags default off; existing sync never claims or queries new entities',async()=>{assert.equal(isV3SignalsEnabled({getItem:()=>null}),false);assert.equal(isV3SignalsSyncEnabled({getItem:()=>null}),false);const signals=await open(),remote=new Remote();await signals.save('daily_readiness',readiness);await sync(signals,remote,{signalsSyncEnabled:false}).syncOnce();assert.equal(remote.tables.daily_readiness.size,0);assert.ok(!remote.calls.includes('daily_readiness'));signals.repository.close();});
test('validation rejects invalid inputs and calculated load cannot be supplied',()=>{assert.throws(()=>validateSignal('daily_readiness',{...readiness,sleep:0}));assert.throws(()=>validateSignal('football_sessions',{...football,minutes_played:91}));assert.equal(validateSignal('football_sessions',{...football,calculated_load:999}).calculated_load,810);});

test('IndexedDB version 2 upgrades add signals without losing workout data',async()=>{const db=new IDBFactory(),request=db.open(databaseNameForUser(A),2);request.onupgradeneeded=()=>request.result.createObjectStore('workout_sessions',{keyPath:'id'});const database=await requestResult(request),transaction=database.transaction('workout_sessions','readwrite');const done=transactionDone(transaction);transaction.objectStore('workout_sessions').put({id:'legacy',owner_id:A,session_date:date,status:'completed'});await done;database.close();const signals=await open(db);assert.ok(signals.repository.database.version>=3);assert.equal((await signals.repository.get('workout_sessions','legacy')).id,'legacy');assert.equal((await signals.list('daily_readiness')).length,0);signals.repository.close();});
test('source changes or tombstones after import block queued data for explicit review',async()=>{const signals=await open(),v2={readiness:[{date,sleep:5,energy:5,fatigue:1,pain:0}]};await importV2Signals(signals,v2);const result=await importV2Signals(signals,{...v2,tombstones:[{entity:'readiness',recordKey:date}]});assert.equal(result.pending_review,1);const row=(await signals.list('daily_readiness'))[0];assert.equal(row.sync_status,'conflict');assert.equal((await signals.coachContext()).readiness.length,0);const remote=new Remote();await sync(signals,remote).syncOnce();assert.equal(remote.tables.daily_readiness.size,0);signals.repository.close();});
test('V3 signal mode does not fall back to a V2 profile when records are absent',async()=>{const signals=await open(),old=globalThis.localStorage;globalThis.localStorage={getItem:key=>{if(key==='v3.signals.enabled')return 'true';throw new Error('Unexpected V2 read.');}};try{const service=new V3CoachService({engine:{repository:signals.repository,history:async()=>[]},featureEnabled:true,now:()=>new Date(`${date}T12:00:00`)});assert.equal((await service.today(null)).signals.readinessScore,null);}finally{globalThis.localStorage=old;signals.repository.close();}});
test('matching remote confirmation cannot clear an explicitly blocked import conflict',async()=>{const signals=await open(),remote=new Remote(),v2={readiness:[{date,sleep:5,energy:5,fatigue:1,pain:0}]};await importV2Signals(signals,v2);await sync(signals,remote).syncOnce();await importV2Signals(signals,{readiness:[{...v2.readiness[0],pain:7}]});const row=(await signals.list('daily_readiness'))[0],server=remote.tables.daily_readiness.get(row.id);remote.tables.daily_readiness.set(row.id,{...server,updated_at:'2026-09-17T00:00:00Z'});await sync(signals,remote).syncOnce();assert.equal((await signals.coachContext()).readiness.length,0);assert.equal((await signals.coachContext()).hasConflicts,true);assert.equal((await signals.repository.get('daily_readiness',row.id)).sync_status,'conflict');signals.repository.close();});

test('additive SQL is idempotent and enforces RLS, ownership, versions and tombstones in PGlite',async()=>{
  const {PGlite}=await import('@electric-sql/pglite'),db=new PGlite();try{
    await db.exec(await readFile(new URL('../supabase/test-v3-local-bootstrap.sql',import.meta.url),'utf8'));
    await db.exec(await readFile(new URL('../supabase/migration-v3-schema.sql',import.meta.url),'utf8'));
    const sql=await readFile(new URL('../supabase/migration-v3-signals.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
    await db.exec(`insert into auth.users(id) values ('${A}'),('${B}') on conflict do nothing; grant usage on schema nico_fit_v3 to authenticated; grant select,insert,update on nico_fit_v3.daily_readiness,nico_fit_v3.football_sessions,nico_fit_v3.match_reviews to authenticated;`);
    await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${A}',false); insert into nico_fit_v3.daily_readiness(id,user_id,local_date,sleep,energy,freshness,pain) values ('${A}','${A}','${date}',5,5,5,0);`);
    await assert.rejects(db.exec(`update nico_fit_v3.daily_readiness set version=3 where id='${A}';`),error=>error.code==='PT409');
    await assert.rejects(db.exec(`update nico_fit_v3.daily_readiness set version=2,user_id='${B}' where id='${A}';`));
    await db.exec(`update nico_fit_v3.daily_readiness set version=2,deleted_at=now() where id='${A}';`);
    await assert.rejects(db.exec(`update nico_fit_v3.daily_readiness set version=3,deleted_at=null where id='${A}';`),error=>error.code==='55000');
    await db.exec(`select set_config('request.jwt.claim.sub','${B}',false);`);assert.equal((await db.query('select * from nico_fit_v3.daily_readiness')).rows.length,0);
    await assert.rejects(db.exec(`insert into nico_fit_v3.football_sessions(id,user_id,local_date,session_type,duration_minutes,rpe) values ('${B}','${A}','${date}','match',90,8);`));
    await db.exec(`select set_config('request.jwt.claim.sub','${A}',false); insert into nico_fit_v3.football_sessions(id,user_id,local_date,session_type,duration_minutes,rpe) values ('${A}','${A}','${date}','match',90,8),('${B}','${A}','${date}','friendly',60,5);`);
    assert.equal((await db.query('select * from nico_fit_v3.football_sessions')).rows.length,2);
    assert.equal(Number((await db.query(`select calculated_load from nico_fit_v3.football_sessions where id='${A}'`)).rows[0].calculated_load),720);
    await assert.rejects(db.exec(`insert into nico_fit_v3.match_reviews(id,user_id,local_date,football_session_id,energy,legs,performance) values ('${A}','${A}','2026-09-16','${A}',4,4,4);`));
    await db.exec(`insert into nico_fit_v3.match_reviews(id,user_id,local_date,football_session_id,energy,legs,performance) values ('${A}','${A}','${date}','${A}',4,4,4);`);
    await assert.rejects(db.exec(`update nico_fit_v3.football_sessions set version=2,session_type='training' where id='${A}';`));
    await db.exec(`select set_config('request.jwt.claim.sub','${B}',false);`);assert.equal((await db.query('select * from nico_fit_v3.match_reviews')).rows.length,0);
  }finally{await db.close();}
});
