import {mayStartNewWork} from '../pwa-update-gate.js';
const node=(tag,text)=>{const value=document.createElement(tag);if(text!=null)value.textContent=text;return value;};
export class V3ObservabilityUI{
  constructor({root,service,onClose,networkEvents=globalThis.window}){Object.assign(this,{root,service,onClose,networkEvents});this.destroyed=false;this.busy=false;this.refreshOnNetwork=()=>this.refresh();}
  async mount(){
    this.root.replaceChildren();const title=node('h1','Estado V3'),close=node('button','Cerrar'),refresh=node('button','Actualizar estado');this.sync=node('button','Sincronizar ahora');this.retry=node('button','Reintentar fallidos');this.summary=node('p');this.summary.setAttribute('role','status');this.facts=node('p');this.status=node('p');this.status.setAttribute('role','status');this.technical=node('pre');const detail=node('details');detail.append(node('summary','Vista técnica (metadatos sin payloads)'),this.technical);
    close.onclick=this.onClose;refresh.onclick=()=>this.refresh();this.sync.onclick=()=>this.inFlight=this.action('syncNow');this.retry.onclick=()=>this.inFlight=this.action('retryFailed');for(const button of [close,refresh,this.sync,this.retry]){button.type='button';button.className='ghost';}
    this.root.append(title,close,refresh,this.summary,this.facts,this.sync,this.retry,this.status,detail);this.networkEvents?.addEventListener('online',this.refreshOnNetwork);this.networkEvents?.addEventListener('offline',this.refreshOnNetwork);await this.refresh();close.focus();
  }
  async refresh(){const generation=this.refreshGeneration=(this.refreshGeneration||0)+1;try{const snapshot=await this.service.snapshot();if(this.destroyed||generation!==this.refreshGeneration)return;this.summary.textContent=snapshot.summary;this.facts.textContent=`${snapshot.online?'Online':'Offline'} · Cola: ${snapshot.queue.operations} · Conflictos: ${snapshot.openConflicts} · Último sync confirmado: ${snapshot.lastSuccessfulSyncAt?new Date(snapshot.lastSuccessfulSyncAt).toLocaleString():'ninguno'}`;this.technical.textContent=JSON.stringify(snapshot,null,2);this.sync.disabled=this.busy||!snapshot.actions.syncNow;this.retry.hidden=!snapshot.backoff.eligibleFailed;this.retry.disabled=this.busy||!snapshot.actions.retryFailed;}catch{if(!this.destroyed&&generation===this.refreshGeneration)this.status.textContent='No se pudo consultar el estado local.';}}
  async action(name){if(this.busy)return;if(!mayStartNewWork()){this.status.textContent='Actualizá esta pestaña antes de iniciar un sync V3.';return;}this.busy=true;this.sync.disabled=true;this.retry.disabled=true;this.status.textContent='Procesando…';try{const result=await this.service[name]();if(!this.destroyed)this.status.textContent=result.skipped==='locked'?'Otra instancia está trabajando.':result.skipped==='offline'?'Offline: la cola se conserva.':'Intento finalizado. Revisá el estado y la confirmación remota.';}catch{if(!this.destroyed)this.status.textContent='No se completó el intento. Los cambios locales se conservan; revisá el diagnóstico.';}finally{this.busy=false;await this.refresh();if(!this.destroyed){const button=name==='syncNow'?this.sync:this.retry;if(!button.disabled&&!button.hidden)button.focus();else this.summary.setAttribute('tabindex','-1'),this.summary.focus();}}}
  destroy(){this.destroyed=true;this.networkEvents?.removeEventListener('online',this.refreshOnNetwork);this.networkEvents?.removeEventListener('offline',this.refreshOnNetwork);}
}
